# Generated by Django 2.0.5 on 2018-05-10 20:04

import django.contrib.gis.db.models.fields
from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20180510_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        AlterSortedManyToManyField(
            model_name='place',
            name='images',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='places.Image'),
        ),
    ]
