# Generated by Django 2.0.5 on 2018-05-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20180513_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='category',
            new_name='categories',
        ),
    ]
