# Generated by Django 2.0.5 on 2018-05-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20180513_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='categories',
        ),
        migrations.AddField(
            model_name='image',
            name='categories',
            field=models.ManyToManyField(to='places.ImageCategory'),
        ),
        migrations.RemoveField(
            model_name='place',
            name='categories',
        ),
        migrations.AddField(
            model_name='place',
            name='categories',
            field=models.ManyToManyField(to='places.PlaceCategory'),
        ),
    ]
