# Generated by Django 2.0.5 on 2018-05-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20180513_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='places.ImageCategory'),
        ),
    ]
