# Generated by Django 2.0.5 on 2018-05-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20180514_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='places.PlaceCategory'),
        ),
    ]
