# Generated by Django 2.0.5 on 2018-05-14 19:52

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20180514_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
