# Generated by Django 2.0.5 on 2018-05-18 14:17

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20180514_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['sort_value']},
        ),
        migrations.RemoveField(
            model_name='address',
            name='current',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
