# Generated by Django 2.0.5 on 2018-05-19 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20180518_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.PlaceChain'),
        ),
    ]
