# Generated by Django 2.0.5 on 2018-05-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_auto_20180519_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='placecategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
