# Generated by Django 2.0.5 on 2018-05-21 14:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_auto_20180520_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='aliases',
            field=models.TextField(blank=True),
        )
    ]
