# Generated by Django 2.0.5 on 2018-05-21 19:58

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_auto_20180521_1417'),
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
