# Generated by Django 2.0.5 on 2018-05-24 13:46

import autoslug.fields
from django.db import migrations

def migrate_slug(apps, schema_editor):
    Place = apps.get_model('places', 'Place')

    for instance in Place.objects.all():
        print(f"Generating slug for {instance}")
        # Will trigger slug update
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_auto_20180521_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, null=True, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='imagecategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='placecategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name'),
        ),
        migrations.RunPython(
            migrate_slug,
            reverse_code=migrations.RunPython.noop
        ),
    ]
