# Generated by Django 2.0.5 on 2018-05-24 13:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_auto_20180524_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title'),
        ),
    ]
