# Generated by Django 2.0.5 on 2018-05-28 02:23

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0024_auto_20180526_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='%Y/%m/%d'),
        ),
    ]
